# Generated by Django 2.1.4 on 2020-07-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=50, verbose_name='Name')),
                ('title2', models.CharField(max_length=50, verbose_name='Surname')),
                ('title3', models.CharField(max_length=50, verbose_name='Country')),
                ('title4', models.CharField(max_length=50, verbose_name='City')),
                ('title5', models.CharField(max_length=50, verbose_name='Street')),
                ('title6', models.CharField(max_length=50, verbose_name='Phone')),
            ],
        ),
    ]
