# Generated by Django 2.1.4 on 2020-07-22 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title4',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title3',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title6',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title5',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title2',
            new_name='surname',
        ),
    ]
